version: "3"
services:
  frontend:
#    stdin_open: true
#    tty: true
    build: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src:ro
  backend:
    restart: always
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "4000:5000"
    volumes:
      - ./backend:/backend:ro
    environment:
      DATABASE_HOSTNAME: postgres  # Name of database service in docker
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: password123
      DATABASE_NAME: closereading_api
      DATABASE_USERNAME: postgres
#      SECRET_KEY:
#      ALGORITHM:
#      ACCESS_TOKEN_EXPIRE_MINUTES: 30
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: closereading_api
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
