# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("https://www.closereading.me/")
    self.driver.set_window_size(1296, 776)
    self.driver.find_element(By.LINK_TEXT, "Books").click()
    self.driver.find_element(By.LINK_TEXT, "Libraries").click()
    self.driver.find_element(By.LINK_TEXT, "Authors").click()
    self.driver.find_element(By.LINK_TEXT, "About").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.CSS_SELECTOR, "center").click()
    self.driver.find_element(By.LINK_TEXT, "Books").click()
    self.driver.find_element(By.LINK_TEXT, "Libraries").click()
    self.driver.find_element(By.LINK_TEXT, "Authors").click()
    self.driver.find_element(By.LINK_TEXT, "About").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "More Info").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(2) .btn").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(3) .btn").click()
    self.driver.find_element(By.LINK_TEXT, "About").click()
    self.driver.execute_script("window.scrollTo(0,354)")
    self.driver.find_element(By.LINK_TEXT, "Postman Documentation").click()
  
